### PR TITLE
Fix coverage reports in ES6.

### LINKED ISSUE #115: Code Climate coverage false positives
This problem existed before your switch to babel, and exists now.

Your code coverage summary generates the below output (note the 0/0 in the summary rows), yet, your icons in your readme indicate 100% coverage.  You get 100% coverage because at one time code climate was receiving actual data from your travis builds, but, it no longer does because the ``coverage/lcov.info`` is now empty in your builds.

```
----------|-----------|-----------|-----------|-----------|
File      |   % Stmts |% Branches |   % Funcs |   % Lines |
----------|-----------|-----------|-----------|-----------|
----------|-----------|-----------|-----------|-----------|
All files |       100 |       100 |       100 |       100 |
----------|-----------|-----------|-----------|-----------|


=============================== Coverage summary ===============================
Statements   : 100% ( 0/0 )
Branches     : 100% ( 0/0 )
Functions    : 100% ( 0/0 )
Lines        : 100% ( 0/0 )
================================================================================
```

The following is from Code Climate support.  I'm looking into a fix myself for my project, but in the meantime this should help you.

-----------------------------
Also, I took a look at your other repository: 6to5-library-boilerplate. It turns out that this same exact issue is occurring there as well. For example, for the latest Travis job, see Line 371: https://travis-ci.org/babel/6to5-library-boilerplate/builds/50725443#L371

That said, for 6to5-library-boilerplate, this didn't used to be case. I looked back through some of your old jobs in Travis, and I can see that up until Job 216, coverage data was being generated and sent to Code Climate just fine. For example, see Line 365 from Job 214: https://travis-ci.org/babel/6to5-library-boilerplate/builds/50718528#L365 For Job 214, note that the coverage summary indicates that a series of statements, branches, functions, and lines were indeed tested.

However, starting with Job 216, that's no longer the case, as 0/0 items are tested and the error from our reporter is being thrown: https://travis-ci.org/babel/6to5-library-boilerplate/builds/50719433#L365 So, something seems to have changed between Jobs 214 and 216, though I'm not sure exactly what changed.

### PR DESCRIPTION
**Pull request by jmeas**
Resolves #115

### CODE REVIEW

File: gulpfile.js [hunk 1]
```diff
@@ -122,6 +122,7 @@ gulp.task('browserify', function() {
 });
 
 gulp.task('coverage', function(done) {
+  require('6to5/register')({ modules: 'common' });
```
Comment (sebmck) [inline gulpfile.js]: `modules` is `"common"` by default.

Comment (jmeas) [inline gulpfile.js]: Ah, yeah? Okay, cool. Will-remove. Thanks @sebmck!
